server:
  port: 8082
spring:
  application:
    name: cache
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    lettuce:
      shutdown-timeout: 100ms
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
eureka:
  instance:
    prefer-ip-address: true
    app-group-name: micro-eureka
    hostname: ${spring.cloud.client.hostname}
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${server.port}}
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/