server:
  port: 8080
spring:
  application:
    name: gateway
eureka:
  instance:
    prefer-ip-address: true
    app-group-name: micro-eureka
    hostname: ${spring.cloud.client.hostname}
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${server.port}}
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/