server:
  port: 8083
spring:
  application:
    name: netty
  rabbitmq:
    host: 49.4.65.228
    port: 5672
    username: guest
    password: guest
#    template:
#      exchange: itc-extern
#      routing-key: itc-extern-interface
#      exchange: spring-boot
#      routing-key: spring-boot-interface

eureka:
  instance:
    prefer-ip-address: true
    app-group-name: micro-eureka
    hostname: ${spring.cloud.client.hostname}
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${server.port}}
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/
netty:
  port: 9999
freeswitch:
  host: 192.168.1.189
  timeout-sec: 10



